version: '3.3'

services:
  furnix-api:
    container_name: furnix-next
    restart: always
    image: node:20.17.0
    ports:
      - 5000:3000
    environment: 
      - PORT=3000

    volumes:
      - ./:/user/src/furnix-next
    working_dir: /user/src/furnix-next

    networks:
      - client-network

    #FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge

# furnix-next: localhost: 5000 <=> container:3000
# furnix-api: localhost: 5001 <=> container:5007
# furnix-batch: localhost: 5002 <=> container:5008
